# Generated by Django 4.1 on 2022-08-11 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_no', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('identity_no', models.CharField(max_length=13)),
                ('gender', models.CharField(max_length=15)),
                ('contacts', models.CharField(max_length=15)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('Zip_code', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=150)),
                ('marital_status', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=150)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('identity_no', models.CharField(max_length=13)),
                ('contacts', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('Zip_code', models.CharField(max_length=10)),
                ('status', models.CharField(default='UNPAID', max_length=100)),
                ('created', models.DateTimeField()),
                ('due', models.DateTimeField()),
                ('paid', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=150)),
                ('processed_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='UNPAID', max_length=100)),
                ('created', models.DateTimeField()),
                ('due', models.DateTimeField()),
                ('paid', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=150)),
                ('processed_by', models.CharField(max_length=100)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='Spouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('identity_no', models.CharField(max_length=13)),
                ('contacts', models.CharField(max_length=15)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=150)),
                ('quote_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.quote')),
            ],
        ),
        migrations.CreateModel(
            name='MemberProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inception', models.DateField()),
                ('Covered', models.DateField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.products')),
            ],
        ),
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('identity_no', models.CharField(max_length=13)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=150)),
                ('invoice_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Dependant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('identity_no', models.CharField(max_length=13)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('identity_no', models.CharField(max_length=13)),
                ('contacts', models.CharField(max_length=15)),
                ('relation', models.TextField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
    ]
