# Generated by Django 4.1 on 2022-08-11 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_product_alter_memberproducts_product_delete_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemberProducts',
            new_name='MemberProduct',
        ),
    ]
