# Generated by Django 4.1 on 2022-08-11 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_memberproducts_memberproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceDetails',
            new_name='InvoiceDetail',
        ),
        migrations.RenameModel(
            old_name='QuoteDetails',
            new_name='QuoteDetail',
        ),
    ]
