# Generated by Django 4.1 on 2022-08-14 10:39

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_memberproduct_covered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberproduct',
            name='Covered',
            field=models.DateField(default=members.models.six_month),
        ),
    ]
