# Generated by Django 4.1 on 2022-09-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_remove_transaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='paid',
            field=models.DateTimeField(null=True),
        ),
    ]
