# Generated by Django 4.1 on 2022-09-29 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_rename_address_quote_city_quote_province_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='identity_no',
        ),
    ]
