# Generated by Django 4.1 on 2022-09-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_quote_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=150),
        ),
    ]
